# -*- coding: utf-8 -*-
"""Stem Cell Bioprocess EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/stem-cell-bioprocess-eda-95ff50d9-1b4c-4d72-91e1-cfc17d820cc2.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20240411/auto/storage/goog4_request%26X-Goog-Date%3D20240411T161829Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D59aa7a921c391407daacde9ee508626a2f3b7b6b2304aacb6e2c97711bc76ee3d361ca04eb5fa749ab02b247c4f935363ebe07131e8ad1e6dfebd12baa91f723c1e954c5c3170717ba783ab750c27082c2651b03ef82ac1979659dcf2b66c6f96b5ed4070c82fe2abdad3b5dcf14ff6f5de10d6ff0c3ec3acbd45d95d4cb43cfedfd21842d0f641181ec75a59c72aafe6fc52c87982a9bcfcbda55f05c658613e42621fcc30b2bf9d7f9bc284cd8ca0ee6158f5b044ee504164ad81cd71987832859be5894296e1b491304bab9bb435c274ba71ab4a032b629b52bbb2f4c7a7e61da8c29da94644a5ecaf9be359beffeefc8606aa65cb2f3328b276e125b5c0d
"""

#first phase



import os
import sys
from tempfile import NamedTemporaryFile
from urllib.request import urlopen
from urllib.parse import unquote, urlparse
from urllib.error import HTTPError
from zipfile import ZipFile
import tarfile
import shutil

CHUNK_SIZE = 40960
DATA_SOURCE_MAPPING = 'stem-cell-content-prediction-in-bioprocess:https%3A%2F%2Fstorage.googleapis.com%2Fkaggle-data-sets%2F1159173%2F1943178%2Fbundle%2Farchive.zip%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com%252F20240411%252Fauto%252Fstorage%252Fgoog4_request%26X-Goog-Date%3D20240411T161829Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3Dd479bc11f42b8101f0f6cef5c263cdf0caf059d02f52a63c00ec587b4570dcb271d007b28cb5451cd664eafea48193d00a5695ca34ef6b1193083b23dbb48f77a4ca6e79db35a24001b30ea938b21e6221c8fbd424f50dd84c30f3c1e2577352ebd8ee2c1286c434f2044243a9dd3289c57f7329e6ae9399fbc254ca875a96bf3fa23270364b923672ce0b48fde7d252b0abb374de60a4fab144afb2f51f47c96bc4aa288b7c354edc2cd9d719356726b71d3dd19df20e977cabf6ea97905013ae1d00fb3c115c79792c3d6ac31a951dede78bb719d95dfd6e1663f1f435c14a6d732f590d1d548f9151469745d306beddbe8c2d274a317acdcbf16a8054f7e2'

KAGGLE_INPUT_PATH='/kaggle/input'
KAGGLE_WORKING_PATH='/kaggle/working'
KAGGLE_SYMLINK='kaggle'

!umount /kaggle/input/ 2> /dev/null
shutil.rmtree('/kaggle/input', ignore_errors=True)
os.makedirs(KAGGLE_INPUT_PATH, 0o777, exist_ok=True)
os.makedirs(KAGGLE_WORKING_PATH, 0o777, exist_ok=True)

try:
  os.symlink(KAGGLE_INPUT_PATH, os.path.join("..", 'input'), target_is_directory=True)
except FileExistsError:
  pass
try:
  os.symlink(KAGGLE_WORKING_PATH, os.path.join("..", 'working'), target_is_directory=True)
except FileExistsError:
  pass

for data_source_mapping in DATA_SOURCE_MAPPING.split(','):
    directory, download_url_encoded = data_source_mapping.split(':')
    download_url = unquote(download_url_encoded)
    filename = urlparse(download_url).path
    destination_path = os.path.join(KAGGLE_INPUT_PATH, directory)
    try:
        with urlopen(download_url) as fileres, NamedTemporaryFile() as tfile:
            total_length = fileres.headers['content-length']
            print(f'Downloading {directory}, {total_length} bytes compressed')
            dl = 0
            data = fileres.read(CHUNK_SIZE)
            while len(data) > 0:
                dl += len(data)
                tfile.write(data)
                done = int(50 * dl / int(total_length))
                sys.stdout.write(f"\r[{'=' * done}{' ' * (50-done)}] {dl} bytes downloaded")
                sys.stdout.flush()
                data = fileres.read(CHUNK_SIZE)
            if filename.endswith('.zip'):
              with ZipFile(tfile) as zfile:
                zfile.extractall(destination_path)
            else:
              with tarfile.open(tfile.name) as tarfile:
                tarfile.extractall(destination_path)
            print(f'\nDownloaded and uncompressed: {directory}')
    except HTTPError as e:
        print(f'Failed to load (likely expired) {download_url} to path {destination_path}')
        continue
    except OSError as e:
        print(f'Failed to load {download_url} to path {destination_path}')
        continue

print('Data source import complete.')

#phase 2


import numpy as np
import pandas as pd
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

"""![](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2659585/bin/rsif20080442f01.jpg)

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2659585/
"""

#phase 3


!pip install openpyxl

#phase 4



df = pd.read_excel('/kaggle/input/stem-cell-content-prediction-in-bioprocess/train_data.xlsx')


df.head()

#phase 5





!pip install dataprep

#phase 6


from dataprep.eda import plot, plot_correlation, create_report, plot_missing

#phase 7


plot_missing(df)

#phase 8
plot(df)

#phase 9



from dataprep.eda import create_report

df = pd.read_excel('/kaggle/input/stem-cell-content-prediction-in-bioprocess/train_data.xlsx')
create_report(df)